version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
      
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    labels:
      - "version-upgrade"

  ####################################
  # 3.x upgrade branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 20
    target-branch: 3.x-upgrade
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
      
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    target-branch: 3.x-upgrade
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
