version: 2
updates:
  - package-ecosystem: maven
    directory: "chapter-2/chapter-2-simple-project"
    schedule:
      interval: "daily"
    labels:
      - "version-upgrade"
    pull-request-branch-name:
      separator: "_"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
