quarkus:
  datasource:
    username: fruits
    password: fruits
    devservices:
      image-name: quay.io/edeandrea/postgres-13-fruits:latest
  hibernate-orm:
    database:
      generation: validate

"%prod":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
