#
# Helm chart to install the Spring Cloud Config server
# Commands to be executed
# kubectl create ns config-storage
# helm install \
#    spring-cloud-config-server kiwigrid/spring-cloud-config-server \
#    -n config-storage \
#    -f src/main/configs/helm.yml
#
# helm delete spring-cloud-config-server -n config-storage
#
config:
  gitUri: https://github.com/ch007m/config-repo
ingress:
  enabled: false
  hosts:
    - host: spring-cloud-config.127.0.0.1.nip.io
      paths:
        - /
