name: Build and test talk

on:
  push:
    branches:
      - quarkus-for-spring-devs-talk
      - quarkus-for-spring-devs-talk-spring-compat
      - quarkus-for-spring-devs-talk-full-quarkus-convert
    paths-ignore:
      - '.github/dependabot.yml'
      - '*.md'
  pull_request:
    branches:
      - quarkus-for-spring-devs-talk
      - quarkus-for-spring-devs-talk-spring-compat
      - quarkus-for-spring-devs-talk-full-quarkus-convert
    paths-ignore:
      - '.github/dependabot.yml'
      - '*.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build
        working-directory: chapter-4/chapter-4-spring-data-jpa
        run: ./mvnw -B clean verify -Dquarkus.http.test-port=0 -Dmaven.compiler.release=17
